# Linear Algebra Operations in Python

In [38]:
import numpy        as np
import scipy.linalg as la
import sympy        as sm
sm.init_printing()

## Reduced Row Echelon Form (RREF)

### Example 1 (p135; Intro2LA 4ed 2009; Gilbert Strang)

In [70]:
A = sm.Matrix([
    [1, 1,  2,  3],
    [2, 2,  8, 10],
    [3, 3, 10, 13]
])
A

⎡1  1  2   3 ⎤
⎢            ⎥
⎢2  2  8   10⎥
⎢            ⎥
⎣3  3  10  13⎦

In [71]:
A.rref()

⎛⎡1  1  0  1⎤        ⎞
⎜⎢          ⎥        ⎟
⎜⎢0  0  1  1⎥, (0, 2)⎟
⎜⎢          ⎥        ⎟
⎝⎣0  0  0  0⎦        ⎠

### Example 2 (p144, Intro2LA 4ed 2009; Gilbert Strang)

In [72]:
A = sm.Matrix([
    [1, 1, 2, 4],
    [1, 2, 2, 5],
    [1, 3, 2, 6]
])
A

⎡1  1  2  4⎤
⎢          ⎥
⎢1  2  2  5⎥
⎢          ⎥
⎣1  3  2  6⎦

In [73]:
A.rref()

⎛⎡1  0  2  3⎤        ⎞
⎜⎢          ⎥        ⎟
⎜⎢0  1  0  1⎥, (0, 1)⎟
⎜⎢          ⎥        ⎟
⎝⎣0  0  0  0⎦        ⎠

In [74]:
L, U, _ = A.LUdecomposition()

⎛⎡1  0  0⎤  ⎡1  1  2  4⎤    ⎞
⎜⎢       ⎥  ⎢          ⎥    ⎟
⎜⎢1  1  0⎥, ⎢0  1  0  1⎥, []⎟
⎜⎢       ⎥  ⎢          ⎥    ⎟
⎝⎣1  2  1⎦  ⎣0  0  0  0⎦    ⎠

## Solve

### Example (Ch3.4; p155; Intro2LA 4ed; Gilbert Strang)

In [78]:
A = sm.Matrix([
    [1, 3, 0, 2],
    [0, 0, 1, 4],
    [1, 3, 1, 6]
])
A

⎡1  3  0  2⎤
⎢          ⎥
⎢0  0  1  4⎥
⎢          ⎥
⎣1  3  1  6⎦

In [79]:
A = sm.Matrix([
    [1, 3, 0, 2, 1],
    [0, 0, 1, 4, 6],
    [1, 3, 1, 6, 7]
])
A

⎡1  3  0  2  1⎤
⎢             ⎥
⎢0  0  1  4  6⎥
⎢             ⎥
⎣1  3  1  6  7⎦

In [80]:
A.rref()

⎛⎡1  3  0  2  1⎤        ⎞
⎜⎢             ⎥        ⎟
⎜⎢0  0  1  4  6⎥, (0, 2)⎟
⎜⎢             ⎥        ⎟
⎝⎣0  0  0  0  0⎦        ⎠

## Matrix Inverse (w/ RREF)

### Example 1

#### Using RREF

In [39]:
A = sm.Matrix([
    [ 2, -1,  0, 1, 0, 0], 
    [-1,  2, -1, 0, 1, 0], 
    [ 0, -1,  2, 0, 0, 1]])
A

⎛⎡1  0  0  3/4  1/2  1/4⎤           ⎞
⎜⎢                      ⎥           ⎟
⎜⎢0  1  0  1/2   1   1/2⎥, (0, 1, 2)⎟
⎜⎢                      ⎥           ⎟
⎝⎣0  0  1  1/4  1/2  3/4⎦           ⎠

In [24]:
A.rref()

⎛⎡1  0  0  3/4  1/2  1/4⎤           ⎞
⎜⎢                      ⎥           ⎟
⎜⎢0  1  0  1/2   1   1/2⎥, (0, 1, 2)⎟
⎜⎢                      ⎥           ⎟
⎝⎣0  0  1  1/4  1/2  3/4⎦           ⎠

#### inverse (SymPy)

In [25]:
A = sm.Matrix([
    [ 2, -1,  0], 
    [-1,  2, -1], 
    [ 0, -1,  2]])
A

⎡2   -1  0 ⎤
⎢          ⎥
⎢-1  2   -1⎥
⎢          ⎥
⎣0   -1  2 ⎦

In [26]:
A**-1

⎡3/4  1/2  1/4⎤
⎢             ⎥
⎢1/2   1   1/2⎥
⎢             ⎥
⎣1/4  1/2  3/4⎦

#### inverse (Numpy)

In [41]:
A = np.array([
    [ 2, -1,  0], 
    [-1,  2, -1], 
    [ 0, -1,  2]])
print(A)

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [42]:
la.inv(A)

array([[0.75, 0.5 , 0.25],
       [0.5 , 1.  , 0.5 ],
       [0.25, 0.5 , 0.75]])

### Example 2

#### Using RREF

In [32]:
A = sm.Matrix([
    [ 1,  0,  0, 1, 0, 0], 
    [ 3,  1,  0, 0, 1, 0], 
    [ 4,  5,  1, 0, 0, 1]])
A

⎡1  0  0  1  0  0⎤
⎢                ⎥
⎢3  1  0  0  1  0⎥
⎢                ⎥
⎣4  5  1  0  0  1⎦

In [33]:
A.rref()

⎛⎡1  0  0  1   0   0⎤           ⎞
⎜⎢                  ⎥           ⎟
⎜⎢0  1  0  -3  1   0⎥, (0, 1, 2)⎟
⎜⎢                  ⎥           ⎟
⎝⎣0  0  1  11  -5  1⎦           ⎠

#### Inverse (SymPy)

In [31]:
A = sm.Matrix([
    [ 1,  0,  0], 
    [ 3,  1,  0], 
    [ 4,  5,  1]])
A

⎡1  0  0⎤
⎢       ⎥
⎢3  1  0⎥
⎢       ⎥
⎣4  5  1⎦

In [30]:
A**-1

⎡1   0   0⎤
⎢         ⎥
⎢-3  1   0⎥
⎢         ⎥
⎣11  -5  1⎦

#### Inverse (NumPy)

In [43]:
A = np.array([
    [ 2, -1,  0], 
    [-1,  2, -1], 
    [ 0, -1,  2]])
print(A)

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [44]:
la.inv(A)

array([[0.75, 0.5 , 0.25],
       [0.5 , 1.  , 0.5 ],
       [0.25, 0.5 , 0.75]])

### Example 3: upper triagular matrix

In [36]:
x, y, z = sm.symbols("x y z")
A = sm.Matrix([
    [ 1,  x,  y], 
    [ 0,  1,  z], 
    [ 0,  0,  1]])
A

⎡1  x  y⎤
⎢       ⎥
⎢0  1  z⎥
⎢       ⎥
⎣0  0  1⎦

In [37]:
A**-1

⎡1  -x  x⋅z - y⎤
⎢              ⎥
⎢0  1     -z   ⎥
⎢              ⎥
⎣0  0      1   ⎦

## LU decomposition

$$A
= \begin{bmatrix} 2 & 1 & 0 \\ 1   & 2   & 1 \\ 0 & 1   & 2   \end{bmatrix}
= \begin{bmatrix} 1 & 0 & 0 \\ 1/2 & 1   & 0 \\ 0 & 2/3 & 1   \end{bmatrix}
  \begin{bmatrix} 2 & 1 & 0 \\ 0   & 3/2 & 1 \\ 0 & 0   & 4/3 \end{bmatrix}
= LU
$$

In [16]:
import numpy as np
import scipy.linalg as la

### Example 1

In [46]:
A = np.array([
    [ 2,  1,  0], 
    [ 1,  2,  1], 
    [ 0,  1,  2]])
print(A)

[[2 1 0]
 [1 2 1]
 [0 1 2]]


In [48]:
P, L, U = la.lu(A)

In [49]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
L

array([[1.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        ],
       [0.        , 0.66666667, 1.        ]])

In [51]:
U

array([[2.        , 1.        , 0.        ],
       [0.        , 1.5       , 1.        ],
       [0.        , 0.        , 1.33333333]])

[Note: LDU decomposition](https://stackoverflow.com/questions/45450175/is-there-a-built-in-easy-ldu-decomposition-method-in-numpy)

In [52]:
A = np.array([
    [ 2,  1,  0], 
    [ 1,  2,  1], 
    [ 0,  1,  2]])

D  = np.diag(np.diag(U)) # D is just the diagonal of U
U /= np.diag(U)[:, None] # Normalize rows of U

In [55]:
D

array([[2.        , 0.        , 0.        ],
       [0.        , 1.5       , 0.        ],
       [0.        , 0.        , 1.33333333]])

In [56]:
U

array([[1.        , 0.5       , 0.        ],
       [0.        , 1.        , 0.66666667],
       [0.        , 0.        , 1.        ]])

### Example 2 (Forward and backward)

$$A
= \begin{bmatrix} 1 & 2 \\ 4 & 9 \end{bmatrix}
= \begin{bmatrix} 1 & 0 \\ 4 & 1 \end{bmatrix}
  \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}
= LU
$$

$$Ax = b => \begin{bmatrix} 1 & 2 \\ 4 & 9 \end{bmatrix}
            \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
          = \begin{bmatrix}  5 \\ 21 \end{bmatrix}$$

$$Lc = b 
=>\begin{bmatrix} 1 & 0 \\ 4 & 1 \end{bmatrix}
  \begin{bmatrix} c_1   \\ c_2 \end{bmatrix}
= \begin{bmatrix} 5     \\ 21 \end{bmatrix}$$

$$Ux = c 
=>\begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}
  \begin{bmatrix} x_1   \\ x_2 \end{bmatrix}
= \begin{bmatrix} c_1   \\ c_2 \end{bmatrix}$$

## Nullspace

### Solve nullspace using SymPy

In [65]:
A = sm.Matrix([
    [1, 1,  2,  3],
    [2, 2,  8, 10],
    [3, 3, 10, 13]
])
A

⎡1  1  2   3 ⎤
⎢            ⎥
⎢2  2  8   10⎥
⎢            ⎥
⎣3  3  10  13⎦

In [67]:
A.nullspace()

⎡⎡-1⎤  ⎡-1⎤⎤
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢1 ⎥  ⎢0 ⎥⎥
⎢⎢  ⎥, ⎢  ⎥⎥
⎢⎢0 ⎥  ⎢-1⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎣⎣0 ⎦  ⎣1 ⎦⎦

In [68]:
A.rref()

⎛⎡1  1  0  1⎤        ⎞
⎜⎢          ⎥        ⎟
⎜⎢0  0  1  1⎥, (0, 2)⎟
⎜⎢          ⎥        ⎟
⎝⎣0  0  0  0⎦        ⎠

In [63]:
U = sm.Matrix([
    [1, 1, 2, 3],
    [0, 0, 4, 4],
    [0, 0, 0, 0]
])
U

⎡1  1  2  3⎤
⎢          ⎥
⎢0  0  4  4⎥
⎢          ⎥
⎣0  0  0  0⎦

In [64]:
U.nullspace()

⎡⎡-1⎤  ⎡-1⎤⎤
⎢⎢  ⎥  ⎢  ⎥⎥
⎢⎢1 ⎥  ⎢0 ⎥⎥
⎢⎢  ⎥, ⎢  ⎥⎥
⎢⎢0 ⎥  ⎢-1⎥⎥
⎢⎢  ⎥  ⎢  ⎥⎥
⎣⎣0 ⎦  ⎣1 ⎦⎦

### Example (Ch3; p146; Intro2LA 4ed; Gilbert Strang)

In [75]:
A = sm.Matrix([
    [1, 3, 0, 2, -1],
    [0, 0, 1, 4, -3],
    [1, 3, 1, 6, -4]
])
A

⎡1  3  0  2  -1⎤
⎢              ⎥
⎢0  0  1  4  -3⎥
⎢              ⎥
⎣1  3  1  6  -4⎦

In [76]:
A.rref()

⎛⎡1  3  0  2  -1⎤        ⎞
⎜⎢              ⎥        ⎟
⎜⎢0  0  1  4  -3⎥, (0, 2)⎟
⎜⎢              ⎥        ⎟
⎝⎣0  0  0  0  0 ⎦        ⎠

In [77]:
A.nullspace()

⎡⎡-3⎤  ⎡-2⎤  ⎡1⎤⎤
⎢⎢  ⎥  ⎢  ⎥  ⎢ ⎥⎥
⎢⎢1 ⎥  ⎢0 ⎥  ⎢0⎥⎥
⎢⎢  ⎥  ⎢  ⎥  ⎢ ⎥⎥
⎢⎢0 ⎥, ⎢-4⎥, ⎢3⎥⎥
⎢⎢  ⎥  ⎢  ⎥  ⎢ ⎥⎥
⎢⎢0 ⎥  ⎢1 ⎥  ⎢0⎥⎥
⎢⎢  ⎥  ⎢  ⎥  ⎢ ⎥⎥
⎣⎣0 ⎦  ⎣0 ⎦  ⎣1⎦⎦

### Solve nullspace using NumPy

In [57]:
A = np.array([
    [1, 1,  2,  3],
    [2, 2,  8, 10],
    [3, 3, 10, 13]
])
A

array([[ 1,  1,  2,  3],
       [ 2,  2,  8, 10],
       [ 3,  3, 10, 13]])

In [59]:
P, L, U = la.lu(A)
U

array([[ 3.        ,  3.        , 10.        , 13.        ],
       [ 0.        ,  0.        ,  1.33333333,  1.33333333],
       [ 0.        ,  0.        , -1.33333333, -1.33333333]])

In [69]:
U = np.array([
    [1, 1, 2, 3],
    [0, 0, 4, 4],
    [0, 0, 0, 0]
])
la.null_space(U)

array([[-0.33825438, -0.69683856],
       [ 0.74489571,  0.21243911],
       [ 0.40664134, -0.48439945],
       [-0.40664134,  0.48439945]])