# The uniqueness of projection operator

set environment

In [1]:
import numpy as np

## Define an example

In [2]:
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4]])
print(X)

[[1 1]
 [1 2]
 [1 3]
 [1 4]]


## Create first Projection matrix

QR decomposition to get a orthonormal basis of col(X)

In [3]:
Qx,R = np.linalg.qr(X)
print(Qx)

[[-0.5         0.67082039]
 [-0.5         0.2236068 ]
 [-0.5        -0.2236068 ]
 [-0.5        -0.67082039]]


Show that it is orthonormal basis

In [4]:
u = Qx[:,0]; v = Qx[:,1]
print(u.dot(u))
print(v.dot(v))
print(u.dot(v))

1.0
0.9999999999999998
8.326672684688674e-17


In [5]:
Px = Qx.dot(Qx.T)
print(Px)

[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


## Create second projection matrix

In [6]:
Y = X[:,[1,0]]
print(Y)

[[1 1]
 [2 1]
 [3 1]
 [4 1]]


QR decomposition to get a orthonormal basis of col(X)

In [7]:
Qy,R = np.linalg.qr(Y)
print(Qy)

[[-1.82574186e-01 -8.16496581e-01]
 [-3.65148372e-01 -4.08248290e-01]
 [-5.47722558e-01 -5.55111512e-17]
 [-7.30296743e-01  4.08248290e-01]]


Show that it is orthonormal basis

In [8]:
u = Qy[:,0]; v = Qy[:,1]
print(u.dot(u))
print(v.dot(v))
print(u.dot(v))

0.9999999999999998
0.9999999999999999
5.551115123125783e-17


In [9]:
Py = Qy.dot(Qy.T)
print(Py)

[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


## Create third projection matrix

In [10]:
Z = X
Z[:,0] = Z[:,0] + Z[:,1]
print(Z)

[[2 1]
 [3 2]
 [4 3]
 [5 4]]


QR decomposition to get a orthonormal basis of col(X)

In [11]:
Qz,R = np.linalg.qr(Z)
print(Qz)

[[-0.27216553 -0.79115481]
 [-0.40824829 -0.36514837]
 [-0.54433105  0.06085806]
 [-0.68041382  0.4868645 ]]


In [12]:
Pz = Qz.dot(Qz.T)
Pz

array([[ 0.7,  0.4,  0.1, -0.2],
       [ 0.4,  0.3,  0.2,  0.1],
       [ 0.1,  0.2,  0.3,  0.4],
       [-0.2,  0.1,  0.4,  0.7]])

## Compare all the projection matrix on the same column space

In [13]:
print(Px)

[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


In [14]:
print(Py)

[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]


In [15]:
print(Pz)

[[ 0.7  0.4  0.1 -0.2]
 [ 0.4  0.3  0.2  0.1]
 [ 0.1  0.2  0.3  0.4]
 [-0.2  0.1  0.4  0.7]]
